name: Build/Efficiency Analysis

on: [push, pull_request]

jobs:
  run:
    runs-on: [ubuntu-latest]
    needs: [build]
    
    steps:
      - name: runexamples
      - uses: actions/checkout@v2
      - run: |
          cd runs
          wget http://www.hepforge.org/archive/cutlang/cms_opendata_ttbar.root
          ./CLA.sh ./cms_opendata_ttbar.root CMSOD -i exLoop.adl -e 10000
          echo "Test execution"
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
   
    - name: make
      run: cd CLA; make
    - name: check
      run: cd ../runs; CLA.sh -h
  
